/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package key.SOURCEDB.SIEBEL;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class S_QUOTE_TNTXM extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 0L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"S_QUOTE_TNTXM\",\"namespace\":\"key.SOURCEDB.SIEBEL\",\"fields\":[{\"name\":\"ROW_ID\",\"type\":{\"type\":\"string\",\"dbColumnName\":\"ROW_ID\",\"length\":15,\"logicalType\":\"VARCHAR\"},\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<S_QUOTE_TNTXM> ENCODER =
      new BinaryMessageEncoder<S_QUOTE_TNTXM>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<S_QUOTE_TNTXM> DECODER =
      new BinaryMessageDecoder<S_QUOTE_TNTXM>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<S_QUOTE_TNTXM> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<S_QUOTE_TNTXM> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<S_QUOTE_TNTXM>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this S_QUOTE_TNTXM to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a S_QUOTE_TNTXM from a ByteBuffer. */
  public static S_QUOTE_TNTXM fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence ROW_ID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public S_QUOTE_TNTXM() {}

  /**
   * All-args constructor.
   * @param ROW_ID The new value for ROW_ID
   */
  public S_QUOTE_TNTXM(java.lang.CharSequence ROW_ID) {
    this.ROW_ID = ROW_ID;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ROW_ID;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ROW_ID = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ROW_ID' field.
   * @return The value of the 'ROW_ID' field.
   */
  public java.lang.CharSequence getROWID() {
    return ROW_ID;
  }

  /**
   * Sets the value of the 'ROW_ID' field.
   * @param value the value to set.
   */
  public void setROWID(java.lang.CharSequence value) {
    this.ROW_ID = value;
  }

  /**
   * Creates a new S_QUOTE_TNTXM RecordBuilder.
   * @return A new S_QUOTE_TNTXM RecordBuilder
   */
  public static key.SOURCEDB.SIEBEL.S_QUOTE_TNTXM.Builder newBuilder() {
    return new key.SOURCEDB.SIEBEL.S_QUOTE_TNTXM.Builder();
  }

  /**
   * Creates a new S_QUOTE_TNTXM RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new S_QUOTE_TNTXM RecordBuilder
   */
  public static key.SOURCEDB.SIEBEL.S_QUOTE_TNTXM.Builder newBuilder(key.SOURCEDB.SIEBEL.S_QUOTE_TNTXM.Builder other) {
    return new key.SOURCEDB.SIEBEL.S_QUOTE_TNTXM.Builder(other);
  }

  /**
   * Creates a new S_QUOTE_TNTXM RecordBuilder by copying an existing S_QUOTE_TNTXM instance.
   * @param other The existing instance to copy.
   * @return A new S_QUOTE_TNTXM RecordBuilder
   */
  public static key.SOURCEDB.SIEBEL.S_QUOTE_TNTXM.Builder newBuilder(key.SOURCEDB.SIEBEL.S_QUOTE_TNTXM other) {
    return new key.SOURCEDB.SIEBEL.S_QUOTE_TNTXM.Builder(other);
  }

  /**
   * RecordBuilder for S_QUOTE_TNTXM instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<S_QUOTE_TNTXM>
    implements org.apache.avro.data.RecordBuilder<S_QUOTE_TNTXM> {

    private java.lang.CharSequence ROW_ID;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(key.SOURCEDB.SIEBEL.S_QUOTE_TNTXM.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ROW_ID)) {
        this.ROW_ID = data().deepCopy(fields()[0].schema(), other.ROW_ID);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing S_QUOTE_TNTXM instance
     * @param other The existing instance to copy.
     */
    private Builder(key.SOURCEDB.SIEBEL.S_QUOTE_TNTXM other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.ROW_ID)) {
        this.ROW_ID = data().deepCopy(fields()[0].schema(), other.ROW_ID);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'ROW_ID' field.
      * @return The value.
      */
    public java.lang.CharSequence getROWID() {
      return ROW_ID;
    }

    /**
      * Sets the value of the 'ROW_ID' field.
      * @param value The value of 'ROW_ID'.
      * @return This builder.
      */
    public key.SOURCEDB.SIEBEL.S_QUOTE_TNTXM.Builder setROWID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.ROW_ID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ROW_ID' field has been set.
      * @return True if the 'ROW_ID' field has been set, false otherwise.
      */
    public boolean hasROWID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ROW_ID' field.
      * @return This builder.
      */
    public key.SOURCEDB.SIEBEL.S_QUOTE_TNTXM.Builder clearROWID() {
      ROW_ID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public S_QUOTE_TNTXM build() {
      try {
        S_QUOTE_TNTXM record = new S_QUOTE_TNTXM();
        record.ROW_ID = fieldSetFlags()[0] ? this.ROW_ID : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<S_QUOTE_TNTXM>
    WRITER$ = (org.apache.avro.io.DatumWriter<S_QUOTE_TNTXM>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<S_QUOTE_TNTXM>
    READER$ = (org.apache.avro.io.DatumReader<S_QUOTE_TNTXM>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
